# Netlify Build Settings for Phudu Project

[build]
  command = "npm run build"  # Command to build the project
  publish = "dist"           # Directory to deploy

# Environment variables
[build.environment]          # Correct syntax for environment table
  NODE_VERSION = "18"      # Specify Node.js version (adjust if needed)

# Redirects and rewrites for Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 